#include "modules\core\player\systems\licences\licence_utils.pwn"
#include "modules\core\player\systems\licences\licence_core.pwn"
#include "modules\core\player\systems\licences\licence_functions.pwn"
#include "modules\core\player\systems\licences\licence_adminscmd.pwn"
#include "modules\core\player\systems\licences\licence_playerscmd.pwn"